# Generated by Django 5.2.6 on 2025-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH')], default='CPF', max_length=10)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('faz_parte_cooperativa', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_coletores/')),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_conta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança')], max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coletor',
                'verbose_name_plural': 'Coletores',
                'ordering': ['nome'],
            },
        ),
    ]
