# Generated by Django 5.2.6 on 2025-09-05 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coletores', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('categoria', models.CharField(choices=[('arrecadacao', 'Arrecadação'), ('repasse', 'Repasse'), ('despesa', 'Despesa'), ('ajuste', 'Ajuste')], default='arrecadacao', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coletor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='coletores.coletor')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='materiais.material')),
            ],
            options={
                'verbose_name': 'Lançamento de Caixa',
                'verbose_name_plural': 'Lançamentos de Caixa',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['data'], name='caixa_lanca_data_311ffa_idx'), models.Index(fields=['categoria', 'data'], name='caixa_lanca_categor_df723f_idx')],
            },
        ),
    ]
