# Generated by Django 5.2.6 on 2025-09-17 16:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('coletores', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocaixa',
            name='quantidade_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lancamentocaixa',
            name='data',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='lancamentocaixa',
            index=models.Index(fields=['material', 'data'], name='caixa_lanca_materia_e22b0c_idx'),
        ),
    ]
